# Sample, not intended to run
services:
  postgres:
    image: postgres
    container_name: postgres-api
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASS}
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - migration     
    ports:
      - 5432:15432

  api:
    image: container/repo/api_image:latest
    container_name: api
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASS}
      POSTGRES_PORT: ${PG_PORT}
      POSTGRES_HOST: ${PG_HOST}
    volumes:
     - ./code_root/api:/container_code/path
    networks:
     - migration
    depends_on:
     - postgres

volumes:
  pg_data:
    name: postgres

networks:
 migration:
