from unittest import mock
from unittest.mock import Mock
import logging

logger = logging.getLogger(__name__)

class cloud_sdk:
    pass


class CloudStorage():
    def __init__(self, bucket_name):
        self.bucket_name = bucket_name
        
    def get_bucket(self):
        if not self.bucket:
            self.bucket = cloud_sdk.bucket(self.bucket_name)
        return self.bucket

    def delete(self, prefix):
        self.bucket.delete(prefix)

class CloudInteractions:
    bucket_name = None
    storage = None

    def __init__(self, bucket):
        self.bucket_name = bucket
        self.storage = None

    @property
    def storage(self):
        if not self.storage:
            self.storage = CloudStorage(self.bucket_name)
        return self.storage

    def delete_from_cloud(self, prefix):
        self.storage.delete(prefix)

    

class MockCloudStorage():
    def __init__(self, bucket_name):
        self.bucket = bucket_name

    def delete(self, filename):
        logger.info("Would have deleted %s/%s", self.bucket, filename)

from copy import copy
# client = MockCloudStorage("fake_bucket")
blob = Mock()
blob.delete = Mock()
mock_bucket = Mock()
mock_bucket.list_blobs = Mock()
mock_bucket.list_blobs.return_value = [blob, blob]
client = Mock()
client.get_bucket = Mock()
client.get_bucket.return_value = mock_bucket
storage = Mock()
storage.Client = Mock()
storage.Client.return_value = client

# Can this be autogenerated? like via magicmock?

import cloud_examples

def test_delete():
    with mock.patch.object(cloud_examples, 'storage', storage):
        cloud_examples.delete("fake_bucket", "fake_prefix")

        # storage.Client.assert_called_once()
        sc = storage.Client()
        sc.get_bucket.assert_called_once()
        bucket = sc.get_bucket()
        bucket.list_blobs.assert_called_once()
        blobs = bucket.list_blobs()
        print(blobs)
        assert blobs[0].delete.call_count == 2

@mock.patch('cloud_examples.storage', autospec=True)
def test_delete_autospec(storage, client_mock):
    # blob = Mock()
    # blob.delete = Mock()
    # mock_bucket = Mock()
    # mock_bucket.list_blobs = Mock()
    # mock_bucket.list_blobs.return_value = [blob, blob]
    # client = Mock()
    # client.get_bucket = Mock()
    # client.get_bucket.return_value = mock_bucket
    storage.Client.return_value = client_mock

    cloud_examples.delete("fake_bucket", "fake_prefix")

    storage.Client.assert_called_once()
    client_mock.get_bucket.assert_called_once()
    client_mock.get_bucket.return_value.list_blobs.assert_called_once()
    blobs = client_mock.get_bucket.return_value.list_blobs.return_value
    assert blobs[0].delete.call_count == 2


# @mock.patch('cloud_examples.storage.Client', autospec=True)
# def test_delete_autospec(mock_client):
#     blob = Mock()
#     blob.delete = Mock()
#     mock_bucket = Mock()
#     mock_bucket.list_blobs = Mock()
#     mock_bucket.list_blobs.return_value = [blob, blob]  
#     mock_client.get_bucket.return_value = mock_bucket
#     cloud_examples.delete("fake_bucket", "fake_prefix")

#     mock_client.return_value.get_bucket.assert_called_with("fake_bucket")
#     mock_list_blobs = mock_client.return_value.get_bucket.return_value.list_blobs
#     mock_list_blobs.assert_called_with(prefix="fake_prefix")
#     blobs = mock_list_blobs.return_value
#     blob = blobs[0]#.return_value
#     assert blob.delete.assert_called_once


#mock storage