# Sample, not intended to run
x-environ: &def-common
  environment:
    &common-env
    POSTGRES_USER: ${PG_USER}
    POSTGRES_PASSWORD: ${PG_PASS}

services:
  postgres:
    image: postgres
    environment:
      <<: *common-env
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - migration     

  api:
    environment:
      <<: *common-env
      POSTGRES_PORT: ${PG_PORT}
      POSTGRES_HOST: ${PG_HOST}
    networks:
     - migration
    depends_on:
     - postgres

volumes:
  pg_data:
    name: postgres

networks:
  migration:

